ARG UBUNTU_VERSION

FROM ubuntu:$UBUNTU_VERSION

# install dependinces
# add lib32z1 for 32-bit support
# CUSTOMIZE: dependinces for building the challenge
RUN apt update && apt upgrade -y && apt install -y build-essential libseccomp-dev libseccomp2

WORKDIR /app

COPY /conf/builder.sh /
RUN ["chmod", "+x", "/builder.sh"]
ENTRYPOINT ["/builder.sh"]
